language: python
install:
    - pip install poetry
    - poetry config virtualenvs.create false
    - (cd review && poetry install -n --no-dev)
script:
    - (cd review && cp sample.env .env && python manage.py graphql_schema --out schema.graphql)
    - git diff --exit-code --name-only
    - (cd review && cp sample.env .env && python manage.py collectstatic)
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/docker_push_dev.sh
    on:
      branch: staging
  - provider: script
    skip_cleanup: true
    script: bash scripts/docker_push.sh
    on:
      tags: true
